mymobilecart/mobileuser/urls.py
from django .urls import path
from mobileuser import views


urlpatterns=[
    path('index',views.IndexView.as_view()),
    path('p_add',views.ProductAddView.as_view(),name='pro_add'),
    path('p_list',views.ProductListView.as_view(),name='pro-list'),
    path('singleview/<str:p_id>',views.SingleProductView.as_view(),name='single_product'),
    path('p_edit/<str:p_id>',views.ProductEditView.as_view(),name='pro_edit'),
    path('p_del/<str:p_id>',views.remove,name='pro-del'),
    path('accounts/signup',views.SignUpView.as_view(),name='sign-up'),
    path('accounts/login',views.LoginView.as_view(),name='mob-user'),
    path('accounts/signout',views.SignOut,name='signout'),
]

mymobilecart/mymobilecart/urls.py
from django.contrib import admin
from django.urls import path,include
from django .conf import settings
from django .conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mobilecart/',include('mobileuser.urls')),
    ] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mymobilecart/mobileuser/models.py
from django.db import models


# Create your models here.
class Users(models.Model):
    username=models.CharField(max_length=80)
    password=models.CharField(max_length=80)

class MobileProducts(models.Model):
    pro_cat=models.CharField(max_length=100)
    pro_code=models.CharField(max_length=100,primary_key=True)
    pro_name=models.CharField(max_length=80)
    pro_ram = models.CharField(max_length=80)
    pro_dis=models.CharField(max_length=90)
    pro_camera = models.CharField(max_length=80)
    pro_battery = models.CharField(max_length=80)
    pro_price=models.PositiveIntegerField()
    pro_offprice=models.PositiveIntegerField(null=True)
    pro_processor=models.CharField(max_length=150)
    pro_warrenty=models.CharField(max_length=150)
    pro_specification=models.CharField(max_length=150)
    pro_img=models.ImageField(upload_to='mobileimages',null=True)

mymobilecart/mobileuser/forms.py
from django import forms
from mobileuser.models import MobileProducts
from django.contrib.auth.models import User
from django .contrib.auth.forms import UserCreationForm


class ProductDetailsAddForm(forms.ModelForm):
    # ProductCode=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    # ProductName = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    # ProductRam = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    # ProductDisplay=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    # ProductCamera = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    # ProductBattery = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    # ProductPrice = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    # ProductOfferPrice = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    # ProductProcessor=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    # ProductWarrenty=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    # ProductSpecification=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    class Meta:
        model=MobileProducts
        fields="__all__"

        widgets={
            'pro_cat':forms.TextInput(attrs={'class':'form-control'}),
            'pro_code':forms.TextInput(attrs={'class':'form-control'}),
            'pro_name':forms.TextInput(attrs={'class':'form-control'}),
            'pro_ram':forms.TextInput(attrs={'class':'form-control'}),
            'pro_dis':forms.TextInput(attrs={'class':'form-control'}),
            'pro_camera':forms.TextInput(attrs={'class':'form-control'}),
            'pro_battery':forms.TextInput(attrs={'class':'form-control'}),
            'pro_price':forms.NumberInput(attrs={'class':'form-control'}),
            'pro_offprice':forms.NumberInput(attrs={'class':'form-control'}),
            'pro_processor':forms.TextInput(attrs={'class':'form-control'}),
            'pro_warrenty':forms.TextInput(attrs={'class':'form-control'}),
            'pro_specification':forms.TextInput(attrs={'class':'form-control'})

        }


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model=User
        fields=[
            'first_name',
            'last_name',
            'email',
            'username',
            'password1',
            'password2'

        ]

class LoginForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'UserName'}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))

mymobilecart/mobileuser/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django .views.generic import View
from mobileuser.forms import LoginForm
from mobileuser.models import Users
from django .contrib import messages
from mobileuser.forms import ProductDetailsAddForm
from mobileuser.models import MobileProducts
from mobileuser.forms import UserRegistrationForm
from django .contrib.auth import authenticate,login,logout


# Create your views here.
class IndexView(View):
    def get(self,request):
        # form=LoginForm()
        return render(request,'index1.html')
# class LoginView(View):
#     form_class = LoginForm
#     template_name='login.html'
#     def get(self,request,*args,**kwargs):
#         form=self.form_class()
#         return render(request,self.template_name,{'form':form})
#     def post(self,request,*args,**kwargs):
#         form=self.form_class(request.POST)
#         if form.is_valid():
#             Users.objects.create(
#                 username=form.cleaned_data.get('username'),
#                 password=form.cleaned_data.get('password')
#                         )
#             messages.success(request,'user added')
#             return  redirect('mob-user')
#         else:
#             messages.error(request,'Cannot add user ')
#             return render(request,'login.html',{'form':form})

class ProductAddView(View):

    def get(self,request,*args,**kwargs):
        form = ProductDetailsAddForm()
        return render(request,'padd.html',{'form':form})
    def post(self,request,*args,**kwargs):
        form=ProductDetailsAddForm(request.POST,files=request.FILES)
        if form.is_valid():
            # MobileProductss.objects.create(
            #     pro_code=form.cleaned_data.get('ProductCode'),
            #     pro_name=form.cleaned_data.get('ProductName'),
            #     pro_ram=form.cleaned_data.get('ProductRam'),
            #     pro_dis=form.cleaned_data.get('ProductDisplay'),
            #     pro_camera=form.cleaned_data.get('ProductCamera'),
            #     pro_battery=form.cleaned_data.get('ProductBattery'),
            #     pro_price=form.cleaned_data.get('ProductPrice'),
            #     pro_offprice=form.cleaned_data.get('ProductOfferPrice'),
            #     pro_processor=form.cleaned_data.get('ProductProcessor'),
            #     pro_warrenty=form.cleaned_data.get('ProductWarrenty'),
            #     pro_specification=form.cleaned_data.get('ProductSpecification'),
            #
            # )
            form.save()
            messages.success(request,'Product added')
            return redirect('pro-list')
        else:
            messages.error(request,'Some error occured')
            return render(request,'padd.html',{'form':form})


class ProductListView(View):
    def get(self,request,*arg,**kwargs):
        product=MobileProducts.objects.all()
        return render(request,'plist.html',{'products':product})

class SingleProductView(View):
    def get(self,request,*args,**kwargs):
        pid=kwargs.get('p_id')
        data=MobileProducts.objects.get(pro_code=pid)
        return render(request,'psingle.html',{'singleproduct':data})

class ProductEditView(View):
    def get(self,request,*args,**kwargs):
        pid = kwargs.get('p_id')
        data = MobileProducts.objects.get(pro_code=pid)
        form=ProductDetailsAddForm(instance=data)
        return render(request,'pedit.html',{'editproduct':form})
    def post(self,request,*args,**kwargs):
        pid=kwargs.get('p_id')
        data=MobileProducts.objects.get(pro_code=pid)
        form=ProductDetailsAddForm(request.POST,instance=data,files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile Edited sucessfully')
            return redirect('pro-list')
        else:
            messages.error(request, 'Profile Editing failed Failed')
            return render(request, 'pedit.html', {'editproduct': form})

def remove(request,*args,**kwargs):
    pid=kwargs.get('p_id')
    data=MobileProducts.objects.get(pro_code=pid)
    data.delete()
    messages.success(request,'employeedeleted')
    return redirect('pro-list')


class SignUpView(View):
    def get(self,request,*args,**kwargs):
        form=UserRegistrationForm()
        return render(request,'signup.html',{'form':form})
    def post(self,request,*args,**kwargs):
        form=UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Registration Success')
            return redirect('mob-user')
        else:
            messages.error(request,'Registration Failed')
            return render(request,'signup.html',{'form':form})

class LoginView(View):
    # form_class = LoginForm
    template_name='logging.html'
    def get(self,request,*args,**kwargs):
        # form=self.form_class()
        return render(request,self.template_name)
    def post(self,request,*args,**kwargs):
        username=request.POST.get('username')
        password=request.POST.get('password1')
        user=authenticate(request,username=username,password=password)
        if user:
            login(request,user)
            # return render(request, 'index1.html')
            return redirect('pro-list')
        else:
            return render(request,'logging.html')



def SignOut(request,*args,**kwargs):
    logout(request)
    return redirect('login')

mymobilecart/mobileuser/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <style>
    .container{
        margin:auto;
        background-color:rgb(237, 228, 234);
        padding:10px;
        border:2px solid,rgba(0,0,0,0);
        width:40%;
    }
  </style>
</head>

<body>
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Mobile Cart</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Product
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'pro-list' %}">Mobile Phones</a></li>
            <li><a class="dropdown-item" href="#">Laptops</a></li>
            <li><a class="dropdown-item" href="#">Smart Watches</a></li>
            <li><a class="dropdown-item" href="#">Smart Bands</a></li>
            <li><a class="dropdown-item" href="#">Other Accessories</a></li>

          </ul>
        </li>

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

<!--        <a href="{%url 'mob-user'%}">SignUp {{request.user}} </a>-->
<!--          <button type="submit" class="btn btn-secondary">


      </button>-->
<ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Product
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'pro-list' %}">Mobile Phones</a></li>
            <li><a class="dropdown-item" href="#">Laptops</a></li>
            <li><a class="dropdown-item" href="#">Smart Watches</a></li>
            <li><a class="dropdown-item" href="#">Smart Bands</a></li>
            <li><a class="dropdown-item" href="#">Other Accessories</a></li>

          </ul>
        </li>




    </div>
  </div>
</nav>

<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="./images/download.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="./images/download.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="./images/download.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

</body>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</html>

mymobilecart/mobileuser/templates/index1.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>My M()bile Cart</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{%static 'styles/index1.css'%}"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href="#page-top">.My MobilE CaRt</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="{%url 'mob-user'%}">

                        </a></li>
                        <li class="nav-item"><a class="nav-link" href="{%url 'sign-up' %}">Sign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="{%url 'mob-user'%}">Log In</a></li>
                         <li class="nav-item"><a class="nav-link" href="{%url 'mob-user'%}">Log out</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="masthead text-center text-white">
            <div class="masthead-content">
                <div class="container px-5">
                    <h1 class="masthead-heading mb-0">Live You Mobi Dreams</h1>
                    <h2 class="masthead-subheading mb-0">Experience Redefined</h2>
                    <a class="btn btn-primary btn-xl rounded-pill mt-5" href="#scroll">Learn More</a>
                </div>
            </div>
            <div class="bg-circle-1 bg-circle"></div>
            <div class="bg-circle-2 bg-circle"></div>
            <div class="bg-circle-3 bg-circle"></div>
            <div class="bg-circle-4 bg-circle"></div>
        </header>
        <!-- Content section 1-->
        <section id="scroll">
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6 order-lg-2">
                        <div class="p-5"><img class="img-fluid rounded-circle" src="{%static 'images/mob.jpg' %}" alt="..." /></div>
                    </div>
                    <div class="col-lg-6 order-lg-1">
                        <div class="p-5">
                            <h2 class="display-4">A phone is more than just a phone...</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Content section 2-->
        <section>
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6">
                        <div class="p-5"><img class="img-fluid rounded-circle" src="{%static 'images/laptop.jpg' %}" alt="..." /></div>
                    </div>
                    <div class="col-lg-6">
                        <div class="p-5">
                            <h2 class="display-4">The future of shopping!</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Content section 3-->
        <section>
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6 order-lg-2">
                        <div class="p-5"><img class="img-fluid rounded-circle" src="{%static 'images/camera.jpg' %}" alt="..." /></div>
                    </div>
                    <div class="col-lg-6 order-lg-1">
                        <div class="p-5">
                            <h2 class="display-4">Stay Focused!</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-black">
            <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>

mymobilecart/mobileuser/templates/logging.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'styles/sign.css'%}">
    <!-- font awosome -->
  <script src="https://kit.fontawesome.com/61d8d73bb4.js" crossorigin="anonymous"></script>
</head>
<body>
<div id="page" class="site">
     <div class="container">
    <div class="wrapper">
        <div class="login">
            <div class="content-heading">
                <div class="y-style">
                    <div class="logo">
                        <a href="#">.Mobile <span>Cart</span></a>
                    </div>
                    <div class="welcome">
                        <h2>Welcome <br>Back! </h2>
                        <p>Get start Creative.</p>

                    </div>
                </div>
            </div>

            <div class="content-form">
                <div class="y-style">
                    <form action="" method="post">
                        {%csrf_token%}
                        <p>
                            <label >Username</label>
                            <input type="text" placeholder="Enter Your Username" name="username" id="id_username">
                        </p>
                        <p>
                            <label >Password</label>
                            <input type="password" placeholder="Enter Your Password" name="password1" id="id_password1">
                        </p>
                        <p class="check">
                            <input type="checkbox" id="remember">
                            <label for="remember">Remember Password</label>
                        </p>
                        <p class="forgot"> <a href="#">Forgot Password</a> </p>
                        <p><button type="submit">Login</button> </p>
                    </form>
                    <div class="afterform">
                        <p>Don't have account?</p>
                        <a href="{% url 'sign-up'%}" class="t-signup">Register</a>
                    </div>
                </div>
            </div>
        </div>
        </div>
     </div>
</div>
</body>
</html>

mymobilecart/mobileuser/templates/padd.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'styles/sign.css'%}">
    <!-- font awosome -->
  <script src="https://kit.fontawesome.com/61d8d73bb4.js" crossorigin="anonymous"></script>
</head>
<body>
<div id="page" class="site">
     <div class="container">
    <div class="wrapper">
        <div class="login">
            <div class="content-heading">
                <div class="y-style">
                    <div class="logo">
                        <a href="#">.Mobile <span>Cart</span></a>
                    </div>
                    <div class="welcome">
                        <h2>Add <br>Product </h2>
                        <p></p>

                    </div>
                </div>
            </div>

            <div class="content-form">
                <div class="y-style">
                    <form action="" method="post" enctype="multipart/form-data">
                        {%csrf_token%}
                        <p>
                            <label >Category</label>
                           <input type="text" name="pro_cat" id="id_pro_cat" placeholder="Enter Category" class="form-control">
                        </p>
                        <p>
                            <label >Product Code</label>

                            <input type="text" name="pro_code" id="id_pro_code" placeholder="Enter Code" class="form-control"></p>
                            <p>
                            <label >Product Name</label>
                        <input type="text" name="pro_name" id="id_pro_name" placeholder="Enter Product Name" class="form-control"></p>
                         <p>
                            <label >Ram</label>
                        <input type="text" name="pro_ram" id="id_pro_ram" placeholder="Ram" class="form-control">
                        </p>

                         <p>
                            <label >Display</label>

                             <input type="text" name="pro_dis" id="id_pro_dis" placeholder="Display" class="form-control"></p>

                         <p>
                            <label> Camera</label>
                        <input type="text" name="pro_camera" id="id_pro_camera" placeholder="Camera" class="form-control"></p>

                         <p>
                            <label >Battery</label>
                        <input type="text" name="pro_battery" id="id_pro_battery" placeholder="Battery" class="form-control"></p>

                         <p>
                            <label >Price</label>
                        <input type="number" name="pro_price" id="id_pro_price" placeholder="Enter Price" class="form-control"></p>
                         <p>
                            <label >Offer Price</label>
                        <input type="number" name="pro_offprice" id="id_pro_offprice" placeholder="Offer Price" class="form-control"></p>


                         <p>
                            <label >Processor</label>
                        <input type="text" name="pro_processor" id="id_processor" placeholder="Processor Details" class="form-control"></p>

                         <p>
                            <label >Warrenty</label>
                        <input type="text" name="pro_warrenty" id="id_warrenty" placeholder="Warrenty" class="form-control"></p>

                         <p>
                            <label >Other Spec</label>
                        <input type="text" name="pro_specification" id="id_pro_specification" placeholder="Other Spec" class="form-control"></p>

                         <p>
                            <label >Image</label>
                        <input type="file" name="pro_img" id="id_pro_img"></p>

                        <p><button type="submit">Add Product</button> </p>
                    </form>

                </div>
            </div>
        </div>
        </div>
     </div>
</div>
</body>
</html>

mymobilecart/mobileuser/templates/productadd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product Details Add</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
<h3><span><center>Please Fill This Form</center></span></h3>
<hr>
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        {%if messages%}
            {% for msg in messages%}
                {% if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS%}
                        <div class="alert alert-success" role="alert">
                          {{msg}}
                        </div>
                {%endif%}
                {%if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
                        <div class="alert alert-danger" role="alert">
                           {{msg}}
                        </div>
                {%endif%}
            {%endfor%}
        {%endif%}
    </div>
    <div class="col-4"></div>
</div>
<div class="container">
            <form action="" method="post" enctype="multipart/form-data">
                {%csrf_token%}

                <div class="row">
                    <div class="col-4">
                        <input type="text" name="pro_cat" id="id_pro_cat" placeholder="Enter Category" class="form-control">
                        <input type="text" name="pro_code" id="id_pro_code" placeholder="Enter Code" class="form-control">
                        <input type="text" name="pro_name" id="id_pro_name" placeholder="Enter Product Name" class="form-control">
                        <input type="text" name="pro_ram" id="id_pro_ram" placeholder="Ram" class="form-control">

                    </div>
                    <div class="col-4">
                         <input type="text" name="pro_dis" id="id_pro_dis" placeholder="Display" class="form-control">
                         <input type="text" name="pro_camera" id="id_pro_camera" placeholder="Camera" class="form-control">
                         <input type="text" name="pro_battery" id="id_pro_battery" placeholder="Battery" class="form-control">
                         <input type="number" name="pro_price" id="id_pro_price" placeholder="Enter Price" class="form-control">
                    </div>
                    <div class="col-4">
                        <input type="number" name="pro_offprice" id="id_pro_offprice" placeholder="Offer Price" class="form-control">
                        <input type="text" name="pro_processor" id="id_processor" placeholder="Processor Details" class="form-control">
                        <input type="text" name="pro_warrenty" id="id_warrenty" placeholder="Warrenty" class="form-control">
                        <input type="text" name="pro_specification" id="id_pro_specification" placeholder="Other Spec" class="form-control">
                        <input type="file" name="pro_img" id="id_pro_img">

                    </div>
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
          </form>
</div>
</div>

</body>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</html>